environment:
  TOKEN:
    secure: 2WHUdcy8QsRWB6OTR7Hf0sWUzXxK9BFGbIvj8zzcsLFXHOra60PQqtik1P0cn1FMozvEFdjOGsjsO5xDedj2uw==

install:
  - npm install
  - npm install -g vsce

build_script:
  - echo publish package
  - vsce publish -p %TOKEN% || true
