environment:
  TOKEN:
    secure: rhlS14UEyUbvvQPr4xBOLEyX+D3rYppZjWlx0DlOt88N4M+kSXInewlFvTMX5dqbAqJuizlz5hm1eE+UN13w2Q==

install:
  - npm install
  - npm install -g vsce

build_script:
  - echo publish package
  - vsce publish -p %TOKEN% || true
