environment:
  TOKEN:
    secure: kqSyCPKqlgMYs49yzJvnK2+E8xltpUwkIupMVOArrrUNrW8S3DoOEtR4YMD4s+3gO+wlWLBUUi/ypIr56GjQaQ==

install:
  - npm install
  - npm install -g vsce

build_script:
  - echo publish package
  - vsce publish -p %TOKEN% || true
